######################################################################
# Automatically generated by qmake (2.01a) Pt 4. mar 13:01:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lGLU

QT += opengl

# Input
HEADERS += Graph4D.h okno.h
SOURCES += Graph4D.cpp 4DLabyrinth.cpp okno.cpp
